### ISSUE TITLE
Locale update needed for mod settings

### ISSUE THREAD

**Issue by 0n0w1c** [pettett/ch-concentrated-solar#1]
--strings.cfg 

[mod-setting-name]
tower-update-interval=Solar Tower Update Interval
full-tower-update-time=Solar Tower Update Time
beam-update-interval=Solar Beam Update Interval
full-beam-update-time=Solar Beam Update Time

[mod-setting-description]
tower-update-interval=Ticks between tower updates
full-tower-update-time=Number of individual towers updated each tower update
beam-update-interval=Ticks between beam updates
full-beam-update-time=Number of individual beams updated each tower update

* or something to this effect, the labels for a couple of the mod startup settings currently display unknown key.

**Comment by pettett** [comment]
(This has been fixed for ages, but I forgot to mark it)
